// Generated by gencpp from file roboy_middleware_msgs/MagneticSensor.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MAGNETICSENSOR_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MAGNETICSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MagneticSensor_
{
  typedef MagneticSensor_<ContainerAllocator> Type;

  MagneticSensor_()
    : id(0)
    , sensor_id()
    , x()
    , y()
    , z()  {
    }
  MagneticSensor_(const ContainerAllocator& _alloc)
    : id(0)
    , sensor_id(_alloc)
    , x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> const> ConstPtr;

}; // struct MagneticSensor_

typedef ::roboy_middleware_msgs::MagneticSensor_<std::allocator<void> > MagneticSensor;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MagneticSensor > MagneticSensorPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MagneticSensor const> MagneticSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ece4c3827719acb61cc1cbe83060dc5";
  }

  static const char* value(const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ece4c3827719acbULL;
  static const uint64_t static_value2 = 0x61cc1cbe83060dc5ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MagneticSensor";
  }

  static const char* value(const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8[] sensor_id\n"
"float32[] x\n"
"float32[] y\n"
"float32[] z\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.sensor_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MagneticSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MagneticSensor_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "sensor_id[]" << std::endl;
    for (size_t i = 0; i < v.sensor_id.size(); ++i)
    {
      s << indent << "  sensor_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.sensor_id[i]);
    }
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MAGNETICSENSOR_H
