// Generated by gencpp from file roboy_middleware_msgs/MotorCalibrationServiceResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MotorCalibrationServiceResponse_
{
  typedef MotorCalibrationServiceResponse_<ContainerAllocator> Type;

  MotorCalibrationServiceResponse_()
    : estimated_spring_parameters()
    , load()
    , displacement()  {
    }
  MotorCalibrationServiceResponse_(const ContainerAllocator& _alloc)
    : estimated_spring_parameters(_alloc)
    , load(_alloc)
    , displacement(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _estimated_spring_parameters_type;
  _estimated_spring_parameters_type estimated_spring_parameters;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _load_type;
  _load_type load;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _displacement_type;
  _displacement_type displacement;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCalibrationServiceResponse_

typedef ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<std::allocator<void> > MotorCalibrationServiceResponse;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorCalibrationServiceResponse > MotorCalibrationServiceResponsePtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MotorCalibrationServiceResponse const> MotorCalibrationServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.estimated_spring_parameters == rhs.estimated_spring_parameters &&
    lhs.load == rhs.load &&
    lhs.displacement == rhs.displacement;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbaac264566b037dc730e8ef15ebdc8f";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcbaac264566b037dULL;
  static const uint64_t static_value2 = 0xc730e8ef15ebdc8fULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MotorCalibrationServiceResponse";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] estimated_spring_parameters\n"
"float64[] load\n"
"float64[] displacement\n"
"\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estimated_spring_parameters);
      stream.next(m.load);
      stream.next(m.displacement);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCalibrationServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MotorCalibrationServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "estimated_spring_parameters[]" << std::endl;
    for (size_t i = 0; i < v.estimated_spring_parameters.size(); ++i)
    {
      s << indent << "  estimated_spring_parameters[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.estimated_spring_parameters[i]);
    }
    s << indent << "load[]" << std::endl;
    for (size_t i = 0; i < v.load.size(); ++i)
    {
      s << indent << "  load[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.load[i]);
    }
    s << indent << "displacement[]" << std::endl;
    for (size_t i = 0; i < v.displacement.size(); ++i)
    {
      s << indent << "  displacement[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.displacement[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCALIBRATIONSERVICERESPONSE_H
