// Generated by gencpp from file roboy_middleware_msgs/MyoBrickCalibrationServiceRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MYOBRICKCALIBRATIONSERVICEREQUEST_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MYOBRICKCALIBRATIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct MyoBrickCalibrationServiceRequest_
{
  typedef MyoBrickCalibrationServiceRequest_<ContainerAllocator> Type;

  MyoBrickCalibrationServiceRequest_()
    : fpga(0)
    , motor(0)
    , degree(0)
    , timeout(0)
    , number_of_data_points(0)
    , min_degree(0.0)
    , max_degree(0.0)  {
    }
  MyoBrickCalibrationServiceRequest_(const ContainerAllocator& _alloc)
    : fpga(0)
    , motor(0)
    , degree(0)
    , timeout(0)
    , number_of_data_points(0)
    , min_degree(0.0)
    , max_degree(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _fpga_type;
  _fpga_type fpga;

   typedef int8_t _motor_type;
  _motor_type motor;

   typedef int8_t _degree_type;
  _degree_type degree;

   typedef int32_t _timeout_type;
  _timeout_type timeout;

   typedef uint32_t _number_of_data_points_type;
  _number_of_data_points_type number_of_data_points;

   typedef float _min_degree_type;
  _min_degree_type min_degree;

   typedef float _max_degree_type;
  _max_degree_type max_degree;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MyoBrickCalibrationServiceRequest_

typedef ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<std::allocator<void> > MyoBrickCalibrationServiceRequest;

typedef boost::shared_ptr< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest > MyoBrickCalibrationServiceRequestPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest const> MyoBrickCalibrationServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fpga == rhs.fpga &&
    lhs.motor == rhs.motor &&
    lhs.degree == rhs.degree &&
    lhs.timeout == rhs.timeout &&
    lhs.number_of_data_points == rhs.number_of_data_points &&
    lhs.min_degree == rhs.min_degree &&
    lhs.max_degree == rhs.max_degree;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01b109725ce2a4cc2c1a8e505f50fa07";
  }

  static const char* value(const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01b109725ce2a4ccULL;
  static const uint64_t static_value2 = 0x2c1a8e505f50fa07ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/MyoBrickCalibrationServiceRequest";
  }

  static const char* value(const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 fpga\n"
"int8 motor\n"
"int8 degree\n"
"int32 timeout\n"
"uint32 number_of_data_points\n"
"float32 min_degree\n"
"float32 max_degree\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fpga);
      stream.next(m.motor);
      stream.next(m.degree);
      stream.next(m.timeout);
      stream.next(m.number_of_data_points);
      stream.next(m.min_degree);
      stream.next(m.max_degree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyoBrickCalibrationServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::MyoBrickCalibrationServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "fpga: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fpga);
    s << indent << "motor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "degree: ";
    Printer<int8_t>::stream(s, indent + "  ", v.degree);
    s << indent << "timeout: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timeout);
    s << indent << "number_of_data_points: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.number_of_data_points);
    s << indent << "min_degree: ";
    Printer<float>::stream(s, indent + "  ", v.min_degree);
    s << indent << "max_degree: ";
    Printer<float>::stream(s, indent + "  ", v.max_degree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MYOBRICKCALIBRATIONSERVICEREQUEST_H
