// Generated by gencpp from file roboy_middleware_msgs/SetInt16.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_SETINT16_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_SETINT16_H

#include <ros/service_traits.h>


#include <roboy_middleware_msgs/SetInt16Request.h>
#include <roboy_middleware_msgs/SetInt16Response.h>


namespace roboy_middleware_msgs
{

struct SetInt16
{

typedef SetInt16Request Request;
typedef SetInt16Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt16
} // namespace roboy_middleware_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_middleware_msgs::SetInt16 > {
  static const char* value()
  {
    return "a4f5a371b10fcd86f80b17a170c1ba59";
  }

  static const char* value(const ::roboy_middleware_msgs::SetInt16&) { return value(); }
};

template<>
struct DataType< ::roboy_middleware_msgs::SetInt16 > {
  static const char* value()
  {
    return "roboy_middleware_msgs/SetInt16";
  }

  static const char* value(const ::roboy_middleware_msgs::SetInt16&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_middleware_msgs::SetInt16Request> should match
// service_traits::MD5Sum< ::roboy_middleware_msgs::SetInt16 >
template<>
struct MD5Sum< ::roboy_middleware_msgs::SetInt16Request>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_middleware_msgs::SetInt16 >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::SetInt16Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_middleware_msgs::SetInt16Request> should match
// service_traits::DataType< ::roboy_middleware_msgs::SetInt16 >
template<>
struct DataType< ::roboy_middleware_msgs::SetInt16Request>
{
  static const char* value()
  {
    return DataType< ::roboy_middleware_msgs::SetInt16 >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::SetInt16Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_middleware_msgs::SetInt16Response> should match
// service_traits::MD5Sum< ::roboy_middleware_msgs::SetInt16 >
template<>
struct MD5Sum< ::roboy_middleware_msgs::SetInt16Response>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_middleware_msgs::SetInt16 >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::SetInt16Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_middleware_msgs::SetInt16Response> should match
// service_traits::DataType< ::roboy_middleware_msgs::SetInt16 >
template<>
struct DataType< ::roboy_middleware_msgs::SetInt16Response>
{
  static const char* value()
  {
    return DataType< ::roboy_middleware_msgs::SetInt16 >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::SetInt16Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_SETINT16_H
