// Generated by gencpp from file roboy_middleware_msgs/InverseKinematicsRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_INVERSEKINEMATICSREQUEST_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_INVERSEKINEMATICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace roboy_middleware_msgs
{
template <class ContainerAllocator>
struct InverseKinematicsRequest_
{
  typedef InverseKinematicsRequest_<ContainerAllocator> Type;

  InverseKinematicsRequest_()
    : endeffector()
    , type(0)
    , target_frame()
    , pose()  {
    }
  InverseKinematicsRequest_(const ContainerAllocator& _alloc)
    : endeffector(_alloc)
    , type(0)
    , target_frame(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _endeffector_type;
  _endeffector_type endeffector;

   typedef int8_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_frame_type;
  _target_frame_type target_frame;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InverseKinematicsRequest_

typedef ::roboy_middleware_msgs::InverseKinematicsRequest_<std::allocator<void> > InverseKinematicsRequest;

typedef boost::shared_ptr< ::roboy_middleware_msgs::InverseKinematicsRequest > InverseKinematicsRequestPtr;
typedef boost::shared_ptr< ::roboy_middleware_msgs::InverseKinematicsRequest const> InverseKinematicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.endeffector == rhs.endeffector &&
    lhs.type == rhs.type &&
    lhs.target_frame == rhs.target_frame &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator1> & lhs, const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_middleware_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04b4751926609088050ec167fcb651ec";
  }

  static const char* value(const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04b4751926609088ULL;
  static const uint64_t static_value2 = 0x050ec167fcb651ecULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_middleware_msgs/InverseKinematicsRequest";
  }

  static const char* value(const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"string endeffector\n"
"\n"
"int8 type\n"
"\n"
"string target_frame\n"
"\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.endeffector);
      stream.next(m.type);
      stream.next(m.target_frame);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InverseKinematicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_middleware_msgs::InverseKinematicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "endeffector: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.endeffector);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "target_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target_frame);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_INVERSEKINEMATICSREQUEST_H
