// Generated by gencpp from file roboy_middleware_msgs/MotorConfigService.msg
// DO NOT EDIT!


#ifndef ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICE_H
#define ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICE_H

#include <ros/service_traits.h>


#include <roboy_middleware_msgs/MotorConfigServiceRequest.h>
#include <roboy_middleware_msgs/MotorConfigServiceResponse.h>


namespace roboy_middleware_msgs
{

struct MotorConfigService
{

typedef MotorConfigServiceRequest Request;
typedef MotorConfigServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorConfigService
} // namespace roboy_middleware_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_middleware_msgs::MotorConfigService > {
  static const char* value()
  {
    return "0aa4adc3b3f52f02aacbfa621182887c";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorConfigService&) { return value(); }
};

template<>
struct DataType< ::roboy_middleware_msgs::MotorConfigService > {
  static const char* value()
  {
    return "roboy_middleware_msgs/MotorConfigService";
  }

  static const char* value(const ::roboy_middleware_msgs::MotorConfigService&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_middleware_msgs::MotorConfigServiceRequest> should match
// service_traits::MD5Sum< ::roboy_middleware_msgs::MotorConfigService >
template<>
struct MD5Sum< ::roboy_middleware_msgs::MotorConfigServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_middleware_msgs::MotorConfigService >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_middleware_msgs::MotorConfigServiceRequest> should match
// service_traits::DataType< ::roboy_middleware_msgs::MotorConfigService >
template<>
struct DataType< ::roboy_middleware_msgs::MotorConfigServiceRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_middleware_msgs::MotorConfigService >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_middleware_msgs::MotorConfigServiceResponse> should match
// service_traits::MD5Sum< ::roboy_middleware_msgs::MotorConfigService >
template<>
struct MD5Sum< ::roboy_middleware_msgs::MotorConfigServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_middleware_msgs::MotorConfigService >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_middleware_msgs::MotorConfigServiceResponse> should match
// service_traits::DataType< ::roboy_middleware_msgs::MotorConfigService >
template<>
struct DataType< ::roboy_middleware_msgs::MotorConfigServiceResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_middleware_msgs::MotorConfigService >::value();
  }
  static const char* value(const ::roboy_middleware_msgs::MotorConfigServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_MIDDLEWARE_MSGS_MESSAGE_MOTORCONFIGSERVICE_H
