// Generated by gencpp from file roboy_cognition_msgs/AssertProperty.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_ASSERTPROPERTY_H
#define ROBOY_COGNITION_MSGS_MESSAGE_ASSERTPROPERTY_H

#include <ros/service_traits.h>


#include <roboy_cognition_msgs/AssertPropertyRequest.h>
#include <roboy_cognition_msgs/AssertPropertyResponse.h>


namespace roboy_cognition_msgs
{

struct AssertProperty
{

typedef AssertPropertyRequest Request;
typedef AssertPropertyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssertProperty
} // namespace roboy_cognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_cognition_msgs::AssertProperty > {
  static const char* value()
  {
    return "096b73ba3a5f0d25198ae92ca0a7239c";
  }

  static const char* value(const ::roboy_cognition_msgs::AssertProperty&) { return value(); }
};

template<>
struct DataType< ::roboy_cognition_msgs::AssertProperty > {
  static const char* value()
  {
    return "roboy_cognition_msgs/AssertProperty";
  }

  static const char* value(const ::roboy_cognition_msgs::AssertProperty&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_cognition_msgs::AssertPropertyRequest> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::AssertProperty >
template<>
struct MD5Sum< ::roboy_cognition_msgs::AssertPropertyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::AssertProperty >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::AssertPropertyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::AssertPropertyRequest> should match
// service_traits::DataType< ::roboy_cognition_msgs::AssertProperty >
template<>
struct DataType< ::roboy_cognition_msgs::AssertPropertyRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::AssertProperty >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::AssertPropertyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_cognition_msgs::AssertPropertyResponse> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::AssertProperty >
template<>
struct MD5Sum< ::roboy_cognition_msgs::AssertPropertyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::AssertProperty >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::AssertPropertyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::AssertPropertyResponse> should match
// service_traits::DataType< ::roboy_cognition_msgs::AssertProperty >
template<>
struct DataType< ::roboy_cognition_msgs::AssertPropertyResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::AssertProperty >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::AssertPropertyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_ASSERTPROPERTY_H
