; Auto-generated. Do not edit!


(cl:in-package roboy_control_msgs-msg)


;//! \htmlinclude MoveEndEffectorResult.msg.html

(cl:defclass <MoveEndEffectorResult> (roslisp-msg-protocol:ros-message)
  ((q
    :reader q
    :initarg :q
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass MoveEndEffectorResult (<MoveEndEffectorResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveEndEffectorResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveEndEffectorResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roboy_control_msgs-msg:<MoveEndEffectorResult> is deprecated: use roboy_control_msgs-msg:MoveEndEffectorResult instead.")))

(cl:ensure-generic-function 'q-val :lambda-list '(m))
(cl:defmethod q-val ((m <MoveEndEffectorResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roboy_control_msgs-msg:q-val is deprecated.  Use roboy_control_msgs-msg:q instead.")
  (q m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveEndEffectorResult>) ostream)
  "Serializes a message object of type '<MoveEndEffectorResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'q))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'q))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveEndEffectorResult>) istream)
  "Deserializes a message object of type '<MoveEndEffectorResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'q) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'q)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveEndEffectorResult>)))
  "Returns string type for a message object of type '<MoveEndEffectorResult>"
  "roboy_control_msgs/MoveEndEffectorResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveEndEffectorResult)))
  "Returns string type for a message object of type 'MoveEndEffectorResult"
  "roboy_control_msgs/MoveEndEffectorResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveEndEffectorResult>)))
  "Returns md5sum for a message object of type '<MoveEndEffectorResult>"
  "2c86974d06038f368935285057a53691")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveEndEffectorResult)))
  "Returns md5sum for a message object of type 'MoveEndEffectorResult"
  "2c86974d06038f368935285057a53691")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveEndEffectorResult>)))
  "Returns full string definition for message of type '<MoveEndEffectorResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32[] q~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveEndEffectorResult)))
  "Returns full string definition for message of type 'MoveEndEffectorResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float32[] q~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveEndEffectorResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'q) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveEndEffectorResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveEndEffectorResult
    (cl:cons ':q (q msg))
))
