(cl:in-package roboy_middleware_msgs-msg)
(cl:export '(ID-VAL
          ID
          CURRENT-VAL
          CURRENT
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          ELBOW_JOINT_ANGLE-VAL
          ELBOW_JOINT_ANGLE
          ELBOW_JOINT_ANGLE_SETPOINT-VAL
          ELBOW_JOINT_ANGLE_SETPOINT
          ELBOW_AGONIST_SETPOINT-VAL
          ELBOW_AGONIST_SETPOINT
          ELBOW_ANTAGONIST_SETPOINT-VAL
          ELBOW_ANTAGONIST_SETPOINT
          WRIST_JOINT_ANGLE-VAL
          WRIST_JOINT_ANGLE
          WRIST_JOINT_ANGLE_SETPOINT-VAL
          WRIST_JOINT_ANGLE_SETPOINT
          WRIST_AGONIST_SETPOINT-VAL
          WRIST_AGONIST_SETPOINT
          WRIST_ANTAGONIST_SETPOINT-VAL
          WRIST_ANTAGONIST_SETPOINT
))