(cl:in-package roboy_middleware_msgs-msg)
(cl:export '(ID-VAL
          ID
          MOTORS-VAL
          MOTORS
          CONTROL_MODE-VAL
          CONTROL_MODE
          OUTPUT_POS_MAX-VAL
          OUTPUT_POS_MAX
          OUTPUT_NEG_MAX-VAL
          OUTPUT_NEG_MAX
          SP_POS_MAX-VAL
          SP_POS_MAX
          SP_NEG_MAX-VAL
          SP_NEG_MAX
          KP-VAL
          KP
          KI-VAL
          KI
          KD-VAL
          KD
          FORWARD_GAIN-VAL
          FORWARD_GAIN
          DEAD_BAND-VAL
          DEAD_BAND
          INTEGRAL_POS_MAX-VAL
          INTEGRAL_POS_MAX
          INTEGRAL_NEG_MAX-VAL
          INTEGRAL_NEG_MAX
          OUTPUT_DIVIDER-VAL
          OUTPUT_DIVIDER
          SETPOINT-VAL
          SETPOINT
))