// Generated by gencpp from file roboy_cognition_msgs/CreateInstance.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_CREATEINSTANCE_H
#define ROBOY_COGNITION_MSGS_MESSAGE_CREATEINSTANCE_H

#include <ros/service_traits.h>


#include <roboy_cognition_msgs/CreateInstanceRequest.h>
#include <roboy_cognition_msgs/CreateInstanceResponse.h>


namespace roboy_cognition_msgs
{

struct CreateInstance
{

typedef CreateInstanceRequest Request;
typedef CreateInstanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CreateInstance
} // namespace roboy_cognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_cognition_msgs::CreateInstance > {
  static const char* value()
  {
    return "257cb06b1a8f1794705928d0364b72b0";
  }

  static const char* value(const ::roboy_cognition_msgs::CreateInstance&) { return value(); }
};

template<>
struct DataType< ::roboy_cognition_msgs::CreateInstance > {
  static const char* value()
  {
    return "roboy_cognition_msgs/CreateInstance";
  }

  static const char* value(const ::roboy_cognition_msgs::CreateInstance&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_cognition_msgs::CreateInstanceRequest> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::CreateInstance >
template<>
struct MD5Sum< ::roboy_cognition_msgs::CreateInstanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::CreateInstance >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::CreateInstanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::CreateInstanceRequest> should match
// service_traits::DataType< ::roboy_cognition_msgs::CreateInstance >
template<>
struct DataType< ::roboy_cognition_msgs::CreateInstanceRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::CreateInstance >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::CreateInstanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_cognition_msgs::CreateInstanceResponse> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::CreateInstance >
template<>
struct MD5Sum< ::roboy_cognition_msgs::CreateInstanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::CreateInstance >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::CreateInstanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::CreateInstanceResponse> should match
// service_traits::DataType< ::roboy_cognition_msgs::CreateInstance >
template<>
struct DataType< ::roboy_cognition_msgs::CreateInstanceResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::CreateInstance >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::CreateInstanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_CREATEINSTANCE_H
