// Generated by gencpp from file roboy_cognition_msgs/DetectIntent.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_DETECTINTENT_H
#define ROBOY_COGNITION_MSGS_MESSAGE_DETECTINTENT_H

#include <ros/service_traits.h>


#include <roboy_cognition_msgs/DetectIntentRequest.h>
#include <roboy_cognition_msgs/DetectIntentResponse.h>


namespace roboy_cognition_msgs
{

struct DetectIntent
{

typedef DetectIntentRequest Request;
typedef DetectIntentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectIntent
} // namespace roboy_cognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_cognition_msgs::DetectIntent > {
  static const char* value()
  {
    return "70b4f9547191039dfd285ee1d326f6c8";
  }

  static const char* value(const ::roboy_cognition_msgs::DetectIntent&) { return value(); }
};

template<>
struct DataType< ::roboy_cognition_msgs::DetectIntent > {
  static const char* value()
  {
    return "roboy_cognition_msgs/DetectIntent";
  }

  static const char* value(const ::roboy_cognition_msgs::DetectIntent&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_cognition_msgs::DetectIntentRequest> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::DetectIntent >
template<>
struct MD5Sum< ::roboy_cognition_msgs::DetectIntentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::DetectIntent >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::DetectIntentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::DetectIntentRequest> should match
// service_traits::DataType< ::roboy_cognition_msgs::DetectIntent >
template<>
struct DataType< ::roboy_cognition_msgs::DetectIntentRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::DetectIntent >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::DetectIntentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_cognition_msgs::DetectIntentResponse> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::DetectIntent >
template<>
struct MD5Sum< ::roboy_cognition_msgs::DetectIntentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::DetectIntent >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::DetectIntentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::DetectIntentResponse> should match
// service_traits::DataType< ::roboy_cognition_msgs::DetectIntent >
template<>
struct DataType< ::roboy_cognition_msgs::DetectIntentResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::DetectIntent >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::DetectIntentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_DETECTINTENT_H
