// Generated by gencpp from file roboy_cognition_msgs/GenerateAnswerRequest.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_GENERATEANSWERREQUEST_H
#define ROBOY_COGNITION_MSGS_MESSAGE_GENERATEANSWERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct GenerateAnswerRequest_
{
  typedef GenerateAnswerRequest_<ContainerAllocator> Type;

  GenerateAnswerRequest_()
    : text_input()  {
    }
  GenerateAnswerRequest_(const ContainerAllocator& _alloc)
    : text_input(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_input_type;
  _text_input_type text_input;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateAnswerRequest_

typedef ::roboy_cognition_msgs::GenerateAnswerRequest_<std::allocator<void> > GenerateAnswerRequest;

typedef boost::shared_ptr< ::roboy_cognition_msgs::GenerateAnswerRequest > GenerateAnswerRequestPtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::GenerateAnswerRequest const> GenerateAnswerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator1> & lhs, const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text_input == rhs.text_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator1> & lhs, const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42190a4ba90a4ddc5e922d0a6d5b790b";
  }

  static const char* value(const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42190a4ba90a4ddcULL;
  static const uint64_t static_value2 = 0x5e922d0a6d5b790bULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/GenerateAnswerRequest";
  }

  static const char* value(const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text_input\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateAnswerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::GenerateAnswerRequest_<ContainerAllocator>& v)
  {
    s << indent << "text_input: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_GENERATEANSWERREQUEST_H
