// Generated by gencpp from file roboy_cognition_msgs/LookAtSpeaker.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_LOOKATSPEAKER_H
#define ROBOY_COGNITION_MSGS_MESSAGE_LOOKATSPEAKER_H

#include <ros/service_traits.h>


#include <roboy_cognition_msgs/LookAtSpeakerRequest.h>
#include <roboy_cognition_msgs/LookAtSpeakerResponse.h>


namespace roboy_cognition_msgs
{

struct LookAtSpeaker
{

typedef LookAtSpeakerRequest Request;
typedef LookAtSpeakerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LookAtSpeaker
} // namespace roboy_cognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_cognition_msgs::LookAtSpeaker > {
  static const char* value()
  {
    return "15a9db50325f4812c0499779cd2dc36e";
  }

  static const char* value(const ::roboy_cognition_msgs::LookAtSpeaker&) { return value(); }
};

template<>
struct DataType< ::roboy_cognition_msgs::LookAtSpeaker > {
  static const char* value()
  {
    return "roboy_cognition_msgs/LookAtSpeaker";
  }

  static const char* value(const ::roboy_cognition_msgs::LookAtSpeaker&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_cognition_msgs::LookAtSpeakerRequest> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::LookAtSpeaker >
template<>
struct MD5Sum< ::roboy_cognition_msgs::LookAtSpeakerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::LookAtSpeaker >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::LookAtSpeakerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::LookAtSpeakerRequest> should match
// service_traits::DataType< ::roboy_cognition_msgs::LookAtSpeaker >
template<>
struct DataType< ::roboy_cognition_msgs::LookAtSpeakerRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::LookAtSpeaker >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::LookAtSpeakerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_cognition_msgs::LookAtSpeakerResponse> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::LookAtSpeaker >
template<>
struct MD5Sum< ::roboy_cognition_msgs::LookAtSpeakerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::LookAtSpeaker >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::LookAtSpeakerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::LookAtSpeakerResponse> should match
// service_traits::DataType< ::roboy_cognition_msgs::LookAtSpeaker >
template<>
struct DataType< ::roboy_cognition_msgs::LookAtSpeakerResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::LookAtSpeaker >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::LookAtSpeakerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_LOOKATSPEAKER_H
