// Generated by gencpp from file roboy_cognition_msgs/RecognizeSpeechResponse.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZESPEECHRESPONSE_H
#define ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZESPEECHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_cognition_msgs
{
template <class ContainerAllocator>
struct RecognizeSpeechResponse_
{
  typedef RecognizeSpeechResponse_<ContainerAllocator> Type;

  RecognizeSpeechResponse_()
    : text()  {
    }
  RecognizeSpeechResponse_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeSpeechResponse_

typedef ::roboy_cognition_msgs::RecognizeSpeechResponse_<std::allocator<void> > RecognizeSpeechResponse;

typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeSpeechResponse > RecognizeSpeechResponsePtr;
typedef boost::shared_ptr< ::roboy_cognition_msgs::RecognizeSpeechResponse const> RecognizeSpeechResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator1> & lhs, const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator1> & lhs, const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roboy_cognition_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_cognition_msgs/RecognizeSpeechResponse";
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"\n"
;
  }

  static const char* value(const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeSpeechResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_cognition_msgs::RecognizeSpeechResponse_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_RECOGNIZESPEECHRESPONSE_H
