// Generated by gencpp from file roboy_cognition_msgs/TrainSeq2Seq.msg
// DO NOT EDIT!


#ifndef ROBOY_COGNITION_MSGS_MESSAGE_TRAINSEQ2SEQ_H
#define ROBOY_COGNITION_MSGS_MESSAGE_TRAINSEQ2SEQ_H

#include <ros/service_traits.h>


#include <roboy_cognition_msgs/TrainSeq2SeqRequest.h>
#include <roboy_cognition_msgs/TrainSeq2SeqResponse.h>


namespace roboy_cognition_msgs
{

struct TrainSeq2Seq
{

typedef TrainSeq2SeqRequest Request;
typedef TrainSeq2SeqResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TrainSeq2Seq
} // namespace roboy_cognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_cognition_msgs::TrainSeq2Seq > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::roboy_cognition_msgs::TrainSeq2Seq&) { return value(); }
};

template<>
struct DataType< ::roboy_cognition_msgs::TrainSeq2Seq > {
  static const char* value()
  {
    return "roboy_cognition_msgs/TrainSeq2Seq";
  }

  static const char* value(const ::roboy_cognition_msgs::TrainSeq2Seq&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_cognition_msgs::TrainSeq2SeqRequest> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::TrainSeq2Seq >
template<>
struct MD5Sum< ::roboy_cognition_msgs::TrainSeq2SeqRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::TrainSeq2Seq >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::TrainSeq2SeqRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::TrainSeq2SeqRequest> should match
// service_traits::DataType< ::roboy_cognition_msgs::TrainSeq2Seq >
template<>
struct DataType< ::roboy_cognition_msgs::TrainSeq2SeqRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::TrainSeq2Seq >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::TrainSeq2SeqRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_cognition_msgs::TrainSeq2SeqResponse> should match
// service_traits::MD5Sum< ::roboy_cognition_msgs::TrainSeq2Seq >
template<>
struct MD5Sum< ::roboy_cognition_msgs::TrainSeq2SeqResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_cognition_msgs::TrainSeq2Seq >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::TrainSeq2SeqResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_cognition_msgs::TrainSeq2SeqResponse> should match
// service_traits::DataType< ::roboy_cognition_msgs::TrainSeq2Seq >
template<>
struct DataType< ::roboy_cognition_msgs::TrainSeq2SeqResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_cognition_msgs::TrainSeq2Seq >::value();
  }
  static const char* value(const ::roboy_cognition_msgs::TrainSeq2SeqResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COGNITION_MSGS_MESSAGE_TRAINSEQ2SEQ_H
