; Auto-generated. Do not edit!


(cl:in-package roboy_control_msgs-msg)


;//! \htmlinclude LookAtFeedback.msg.html

(cl:defclass <LookAtFeedback> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type cl:float
    :initform 0.0))
)

(cl:defclass LookAtFeedback (<LookAtFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LookAtFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LookAtFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roboy_control_msgs-msg:<LookAtFeedback> is deprecated: use roboy_control_msgs-msg:LookAtFeedback instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <LookAtFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roboy_control_msgs-msg:error-val is deprecated.  Use roboy_control_msgs-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LookAtFeedback>) ostream)
  "Serializes a message object of type '<LookAtFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LookAtFeedback>) istream)
  "Deserializes a message object of type '<LookAtFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'error) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LookAtFeedback>)))
  "Returns string type for a message object of type '<LookAtFeedback>"
  "roboy_control_msgs/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LookAtFeedback)))
  "Returns string type for a message object of type 'LookAtFeedback"
  "roboy_control_msgs/LookAtFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LookAtFeedback>)))
  "Returns md5sum for a message object of type '<LookAtFeedback>"
  "417c68e466c6131d4fed652219a9ccb7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LookAtFeedback)))
  "Returns md5sum for a message object of type 'LookAtFeedback"
  "417c68e466c6131d4fed652219a9ccb7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LookAtFeedback>)))
  "Returns full string definition for message of type '<LookAtFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LookAtFeedback)))
  "Returns full string definition for message of type 'LookAtFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LookAtFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LookAtFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LookAtFeedback
    (cl:cons ':error (error msg))
))
