// Generated by gencpp from file roboy_simulation_msgs/GymStep.msg
// DO NOT EDIT!


#ifndef ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEP_H
#define ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEP_H

#include <ros/service_traits.h>


#include <roboy_simulation_msgs/GymStepRequest.h>
#include <roboy_simulation_msgs/GymStepResponse.h>


namespace roboy_simulation_msgs
{

struct GymStep
{

typedef GymStepRequest Request;
typedef GymStepResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GymStep
} // namespace roboy_simulation_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_simulation_msgs::GymStep > {
  static const char* value()
  {
    return "da078c4985541d376efaaa93946e1b7b";
  }

  static const char* value(const ::roboy_simulation_msgs::GymStep&) { return value(); }
};

template<>
struct DataType< ::roboy_simulation_msgs::GymStep > {
  static const char* value()
  {
    return "roboy_simulation_msgs/GymStep";
  }

  static const char* value(const ::roboy_simulation_msgs::GymStep&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_simulation_msgs::GymStepRequest> should match
// service_traits::MD5Sum< ::roboy_simulation_msgs::GymStep >
template<>
struct MD5Sum< ::roboy_simulation_msgs::GymStepRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_simulation_msgs::GymStep >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::GymStepRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_simulation_msgs::GymStepRequest> should match
// service_traits::DataType< ::roboy_simulation_msgs::GymStep >
template<>
struct DataType< ::roboy_simulation_msgs::GymStepRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_simulation_msgs::GymStep >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::GymStepRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_simulation_msgs::GymStepResponse> should match
// service_traits::MD5Sum< ::roboy_simulation_msgs::GymStep >
template<>
struct MD5Sum< ::roboy_simulation_msgs::GymStepResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_simulation_msgs::GymStep >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::GymStepResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_simulation_msgs::GymStepResponse> should match
// service_traits::DataType< ::roboy_simulation_msgs::GymStep >
template<>
struct DataType< ::roboy_simulation_msgs::GymStepResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_simulation_msgs::GymStep >::value();
  }
  static const char* value(const ::roboy_simulation_msgs::GymStepResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_SIMULATION_MSGS_MESSAGE_GYMSTEP_H
